/* eslint-disable */
// This file was generated by script
// this file is used to generate icon names from files within this directory
// icons are used in Icon component

import closeMe from './close-me.svg';

const icons = {
  closeMe
};

export default icons;
